# Generated by Django 2.1.11 on 2020-01-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200118_0716'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='name',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
