# Generated by Django 2.1.11 on 2020-01-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisan',
            name='phone',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AlterField(
            model_name='artisan',
            name='name',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
