# Generated by Django 2.1.11 on 2020-01-18 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20200118_0737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisan',
            name='user',
        ),
    ]
